- id: '1613574979356'
  alias: Afzuiging
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  - platform: time
    at: '23:00'
  - platform: time
    at: 06:00
  - platform: time
    at: 09:00
  condition: []
  action:
  - type: toggle
    device_id: 4fd8739fc31b27e05ad9bbeb55f8e553
    entity_id: switch.extraction
    domain: switch
  mode: single
- id: '1613575245765'
  alias: 'Roomba: started cleaning'
  description: ''
  trigger:
  - platform: device
    device_id: 7642ad1b24188c6f1cb3d50f909e1a6f
    domain: vacuum
    entity_id: vacuum.chantall
    type: cleaning
  - platform: state
    entity_id: vacuum.chantall
    attribute: status
    to: cleaning
  condition: []
  action:
  - service: notify.mobile_app_oneplus_nord
    data:
      title: Roomba
      message: Chantall started to clean!
  mode: single
- id: '1613575275607'
  alias: 'Roomba: stopped cleaning'
  description: ''
  trigger:
  - platform: state
    entity_id: vacuum.chantall
    to: docked
    from: returning
  condition: []
  action:
  - service: notify.mobile_app_oneplus_nord
    data:
      title: Roomba
      message: Chantall finished cleaning!
  mode: single
- id: '1614244821908'
  alias: Roomba stuck
  description: ''
  trigger:
  - platform: state
    entity_id: vacuum.chantall
    attribute: status
    to: stuck
  condition: []
  action:
  - device_id: a6937089cecaef3bf1b00dece90ddd06
    domain: mobile_app
    type: notify
    message: Chantall is stuck go safe here!
    title: Roomba
  mode: single
- id: '1614245267176'
  alias: GFT
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.recycleapp_gft
    attribute: Days-until
    to: '1'
  condition:
  - condition: time
    after: '19:00'
  action:
  - device_id: a6937089cecaef3bf1b00dece90ddd06
    domain: mobile_app
    type: notify
    message: Put the GFT outside! Or tell Lia to do it :)
    title: Garbage
  mode: single
