- id: '1613574979356'
  alias: Afzuiging
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  - platform: time
    at: '21:00'
  condition: []
  action:
  - type: toggle
    device_id: 4fd8739fc31b27e05ad9bbeb55f8e553
    entity_id: switch.extraction
    domain: switch
  mode: single
- id: '1613575245765'
  alias: 'Roomba: started cleaning'
  description: ''
  trigger:
  - platform: device
    device_id: 7642ad1b24188c6f1cb3d50f909e1a6f
    domain: vacuum
    entity_id: vacuum.chantall
    type: cleaning
  - platform: state
    entity_id: vacuum.chantall
    attribute: status
    to: cleaning
  condition: []
  action:
  - service: notify.mobile_app_oneplus_nord
    data:
      title: Roomba
      message: Chantall started to clean!
  mode: single
- id: '1613575275607'
  alias: 'Roomba: stopped cleaning'
  description: ''
  trigger:
  - platform: state
    entity_id: vacuum.chantall
    to: docked
    from: returning
  condition: []
  action:
  - service: notify.mobile_app_oneplus_nord
    data:
      title: Roomba
      message: Chantall finished cleaning!
  mode: single
- id: '1613655082689'
  alias: 'Frontend: change theme'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.theme
  - platform: state
    entity_id: input_boolean.dark_mode
  - platform: state
    entity_id: input_boolean.theme_alternative
  - platform: homeassistant
    event: start
  condition: []
  action:
    service: frontend.set_theme
    data:
      name: '{% set which = "dark" if is_state("input_boolean.dark_mode", "on") else
        "light" -%} {% set name = states("input_select.theme") -%} {% set suffix =
        "-alternative" if is_state("input_boolean.theme_alternative", "on") else ""
        -%} ios-{{ which }}-mode-{{ name }}{{ suffix }}

        '
  mode: single
- id: '1614243890856'
  alias: Auto lights
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.oneplus_nord
    zone: zone.home
    event: enter
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'on'
  mode: single
- id: '1614244821908'
  alias: Roomba stuck
  description: ''
  trigger:
  - platform: state
    entity_id: vacuum.chantall
    attribute: status
    to: stuck
  condition: []
  action:
  - device_id: a6937089cecaef3bf1b00dece90ddd06
    domain: mobile_app
    type: notify
    message: Chantall is stuck go save her!
    title: Roomba
  mode: single
- id: '1614245267176'
  alias: GFT
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.recycleapp_gft
    attribute: Days-until
    to: '1'
  condition:
  - condition: time
    after: '19:00'
  action:
  - device_id: a6937089cecaef3bf1b00dece90ddd06
    domain: mobile_app
    type: notify
    message: Put the GFT outside! Or tell Lia to do it :)
    title: Garbage
  mode: single
