
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

sensor: !include includes/sensors.yaml
input_select: !include includes/input_selects.yaml
light: !include includes/lights.yaml
spotify: !include includes/spotify.yaml

# Text to speech
tts:
  - platform: google_translate


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
