- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3
    - light.kitchen_4
- platform: group
  name: Office Lights
  entities:
    - light.office_1
    - light.office_2
